# frozen_string_literal: true
# 業種
industry_categories =
  [{ name: '金融・保険',
     industries: [{ name: '銀行・信託銀行' },
                  { name: '信用金庫・組合' },
                  { name: '証券' },
                  { name: '投資銀行' },
                  { name: 'アセットマネジメント' },
                  { name: 'プライベートエクイティ・ファンド' },
                  { name: '不動産ファンド' },
                  { name: 'ベンチャーキャピタル' },
                  { name: 'クレジット・信販' },
                  { name: '政府系金融機関' },
                  { name: 'その他（金融）' },
                  { name: '生命保険' },
                  { name: '損害保険' },
                  { name: 'その他（保険）' }] },
   { name: '建設・不動産',
     industries: [{ name: '建設・建築・土木' },
                  { name: '設備・電気' },
                  { name: '住宅設備・ハウスメーカー' },
                  { name: 'プラント・エンジニアリング' },
                  { name: '内装・リフォーム・インテリア' },
                  { name: 'その他（建設）' },
                  { name: 'デベロッパー' },
                  { name: '不動産仲介' },
                  { name: '不動産管理' },
                  { name: 'その他（不動産）' }] },
   { name: 'コンサルティング・士業',
     industries: [{ name: 'コンサルティング' },
                  { name: 'シンクタンク' },
                  { name: 'リサーチ' },
                  { name: 'その他（コンサルティング）' },
                  { name: '監査・税理士法人' },
                  { name: '法律事務所' },
                  { name: 'その他（士業）' }] },
   { name: 'IT・インターネット',
     industries: [{ name: 'インターネットサービス' },
                  { name: 'デジタルマーケティング' },
                  { name: 'SIer' },
                  { name: 'ソフトウェア' },
                  { name: 'ハードウェア' },
                  { name: '通信・キャリア' },
                  { name: 'その他（IT・インターネット）' }] },
   { name: 'メーカー・商社',
     industries: [{ name: '電気・電子' },
                  { name: '半導体' },
                  { name: '機械' },
                  { name: '精密・計測機器' },
                  { name: '自動車・自動車部品' },
                  { name: '化学・石油' },
                  { name: 'バイオ' },
                  { name: '素材' },
                  { name: '食品・飲料' },
                  { name: '日用品' },
                  { name: '化粧品' },
                  { name: 'アパレル・ファッション' },
                  { name: 'その他（メーカー）' },
                  { name: '総合商社' },
                  { name: '専門商社' }] },
   { name: '流通・小売・サービス',
     industries: [{ name: '流通' },
                  { name: '小売' },
                  { name: 'その他（流通・小売）' },
                  { name: '人材紹介・人材派遣' },
                  { name: 'アウトソーシング・コールセンター' },
                  { name: '旅行・観光' },
                  { name: 'ホテル' },
                  { name: 'アミューズメント' },
                  { name: '福祉・介護' },
                  { name: '外食' },
                  { name: 'ブライダル' },
                  { name: 'その他（サービス）' }] },
   { name: 'メディカル',
     industries: [{ name: '医薬品メーカー' },
                  { name: '医療機器メーカー' },
                  { name: '医薬品卸' },
                  { name: '医療機器卸' },
                  { name: '病院・クリニック' },
                  { name: '大学・研究施設' },
                  { name: 'CRO' },
                  { name: '臨床検査機器・診断薬' },
                  { name: 'ドラッグストア・調剤薬局' },
                  { name: '再生医療・バイオベンチャー' },
                  { name: 'その他（メディカル）' }] },
   { name: 'マスコミ・メディア',
     industries: [{ name: '広告・PR' },
                  { name: 'テレビ・放送・映像・音響' },
                  { name: '新聞・出版' },
                  { name: '印刷' },
                  { name: 'その他（マスコミ・メディア）' }] },
   { name: 'エンターテインメント',
     industries: [{ name: '音楽' },
                  { name: '映画' },
                  { name: 'ゲーム' },
                  { name: 'その他（エンターテインメント）' }] },
   { name: '運輸・物流',
     industries: [{ name: '海運' },
                  { name: '鉄道' },
                  { name: '陸運' },
                  { name: '空輸' },
                  { name: '空港' },
                  { name: 'その他（運輸・交通）' },
                  { name: '物流' },
                  { name: '倉庫' },
                  { name: 'その他（物流・倉庫）' }] },
   { name: 'エネルギー',
     industries: [{ name: '電気・ガス・水道' },
                  { name: '石油' },
                  { name: 'エネルギー' },
                  { name: 'その他（エネルギー）' }] },
   { name: 'その他',
     industries: [{ name: '教育' },
                  { name: '官公庁' },
                  { name: '自治体' },
                  { name: '農林・水産' },
                  { name: 'その他' }] }]

industry_categories.each do |industry_category|
  IndustryCategory.find_or_create_by!(name: industry_category[:name])
  industry_category[:industries].each do |industry|
    Industry.find_or_create_by!(name: industry[:name],
                                industry_category_id: IndustryCategory.find_by(name: industry_category[:name]).id)
  end
end
